### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by naderi** [Pushplaybang/wordpress-docker-local-environment#1] opened 2017-01-19 10:41 UTC
Hi, I get the **502 Bad Gateway** error, even if I don't change anything in your files.
I am working on a Windows 10 64bit machine with the latest docker version.

**Comment by Pushplaybang** [comment] 2017-02-03 06:30
Hey There @naderi 

can you explain a little more about when this error appears?  I've only tested reasonably under OSX so far, would love to get at issues for Windows if we can.

**Comment by Pushplaybang** [comment] 2017-02-13 08:21
@naderi  - any word on this?

**Comment by Pushplaybang** [comment] 2017-04-29 21:58
Hi naderi

I'm unable to reproduce this issue, I'm going to close this for now, the repo has gone through a few changes so I would suggest having a look at the latest version, though I'm unable to test on Windows currently.  

Would greatly appreciate any additional input/  feedback, please feel free to reopen this.

**Closed by Pushplaybang** 2017-04-29 21:58 UTC
